//===================================================================================
// Microsoft patterns & practices
// Composite Application Guidance for Windows Presentation Foundation and Silverlight
//===================================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===================================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===================================================================================
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewSwitchingNavigation.Tests.AcceptanceTest.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlIdentifiers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlIdentifiers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewSwitchingNavigation.Tests.AcceptanceTest.TestData.ControlIdentifiers", typeof(ControlIdentifiers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalendarGrid.
        /// </summary>
        internal static string CalendarGrid_Silverlight {
            get {
                return ResourceManager.GetString("CalendarGrid_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalendarRadioButton.
        /// </summary>
        internal static string CalendarRadioButton_Silverlight {
            get {
                return ResourceManager.GetString("CalendarRadioButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactAvatarsRadioButton.
        /// </summary>
        internal static string ContactAvatarsRadioButton_Silverlight {
            get {
                return ResourceManager.GetString("ContactAvatarsRadioButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactDetailsRadioButton.
        /// </summary>
        internal static string ContactDetailsRadioButton_Silverlight {
            get {
                return ResourceManager.GetString("ContactDetailsRadioButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactsList.
        /// </summary>
        internal static string ContactsList_Silverlight {
            get {
                return ResourceManager.GetString("ContactsList_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailRadioButton.
        /// </summary>
        internal static string EmailRadioButton_Silverlight {
            get {
                return ResourceManager.GetString("EmailRadioButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailTextBlock.
        /// </summary>
        internal static string EmailTextBlock_Silverlight {
            get {
                return ResourceManager.GetString("EmailTextBlock_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailTextBox.
        /// </summary>
        internal static string EmailTextBox_Silverlight {
            get {
                return ResourceManager.GetString("EmailTextBox_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromDataBlock.
        /// </summary>
        internal static string FromDataBlock_Silverlight {
            get {
                return ResourceManager.GetString("FromDataBlock_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessagesList.
        /// </summary>
        internal static string MessagesList_Silverlight {
            get {
                return ResourceManager.GetString("MessagesList_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NewButton {
            get {
                return ResourceManager.GetString("NewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenButton.
        /// </summary>
        internal static string OpenButton_Silverlight {
            get {
                return ResourceManager.GetString("OpenButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenMailHyperLink.
        /// </summary>
        internal static string OpenMailHyperLink {
            get {
                return ResourceManager.GetString("OpenMailHyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string ReplyButton {
            get {
                return ResourceManager.GetString("ReplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View-Switching Navigation.
        /// </summary>
        internal static string SilverlightAppTitle {
            get {
                return ResourceManager.GetString("SilverlightAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectBlock.
        /// </summary>
        internal static string SubjectBlock_Silverlight {
            get {
                return ResourceManager.GetString("SubjectBlock_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectDataBlock.
        /// </summary>
        internal static string SubjectDataBlock_Silverlight {
            get {
                return ResourceManager.GetString("SubjectDataBlock_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectTextBox.
        /// </summary>
        internal static string SubjectTextBox_Silverlight {
            get {
                return ResourceManager.GetString("SubjectTextBox_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlockEmailData.
        /// </summary>
        internal static string TextBlockEmailData_Silverlight {
            get {
                return ResourceManager.GetString("TextBlockEmailData_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlockFromData.
        /// </summary>
        internal static string TextBlockFromData_Silverlight {
            get {
                return ResourceManager.GetString("TextBlockFromData_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlockSubject.
        /// </summary>
        internal static string TextBlockSubject_Silverlight {
            get {
                return ResourceManager.GetString("TextBlockSubject_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlockSubjectData.
        /// </summary>
        internal static string TextBlockSubjectData_Silverlight {
            get {
                return ResourceManager.GetString("TextBlockSubjectData_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlockTo.
        /// </summary>
        internal static string TextBlockTo_Silverlight {
            get {
                return ResourceManager.GetString("TextBlockTo_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlockToData.
        /// </summary>
        internal static string TextBlockToData_Silverlight {
            get {
                return ResourceManager.GetString("TextBlockToData_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToBlock.
        /// </summary>
        internal static string ToBlock_Silverlight {
            get {
                return ResourceManager.GetString("ToBlock_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToBlockData.
        /// </summary>
        internal static string ToBlockData_Silverlight {
            get {
                return ResourceManager.GetString("ToBlockData_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToTextBox.
        /// </summary>
        internal static string ToTextBox_Silverlight {
            get {
                return ResourceManager.GetString("ToTextBox_Silverlight", resourceCulture);
            }
        }
    }
}
