//===================================================================================
// Microsoft patterns & practices
// Composite Application Guidance for Windows Presentation Foundation and Silverlight
//===================================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===================================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===================================================================================
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modularity.Tests.AcceptanceTest.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlIdentifiers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlIdentifiers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modularity.Tests.AcceptanceTest.TestData.ControlIdentifiers", typeof(ControlIdentifiers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Module C.
        /// </summary>
        internal static string LoadModuleC_Silverlight {
            get {
                return ResourceManager.GetString("LoadModuleC_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Module C.
        /// </summary>
        internal static string LoadModuleC_Wpf {
            get {
                return ResourceManager.GetString("LoadModuleC_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Module X.
        /// </summary>
        internal static string LoadModuleX_Silverlight {
            get {
                return ResourceManager.GetString("LoadModuleX_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Module X.
        /// </summary>
        internal static string LoadModuleX_Wpf {
            get {
                return ResourceManager.GetString("LoadModuleX_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module A Loaded.
        /// </summary>
        internal static string ModuleALoaded_Silverlight {
            get {
                return ResourceManager.GetString("ModuleALoaded_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module A Loaded.
        /// </summary>
        internal static string ModuleALoaded_Wpf {
            get {
                return ResourceManager.GetString("ModuleALoaded_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module B Loaded.
        /// </summary>
        internal static string ModuleBLoaded_Silverlight {
            get {
                return ResourceManager.GetString("ModuleBLoaded_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module B Loaded.
        /// </summary>
        internal static string ModuleBLoaded_Wpf {
            get {
                return ResourceManager.GetString("ModuleBLoaded_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module C Loaded.
        /// </summary>
        internal static string ModuleCLoaded_Silverlight {
            get {
                return ResourceManager.GetString("ModuleCLoaded_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module C Loaded.
        /// </summary>
        internal static string ModuleCLoaded_Wpf {
            get {
                return ResourceManager.GetString("ModuleCLoaded_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module D Loaded.
        /// </summary>
        internal static string ModuleDLoaded_Silverlight {
            get {
                return ResourceManager.GetString("ModuleDLoaded_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module D Loaded.
        /// </summary>
        internal static string ModuleDLoaded_Wpf {
            get {
                return ResourceManager.GetString("ModuleDLoaded_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module W Loaded.
        /// </summary>
        internal static string ModuleWLoaded_Silverlight {
            get {
                return ResourceManager.GetString("ModuleWLoaded_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module X Loaded.
        /// </summary>
        internal static string ModuleXLoaded_Silverlight {
            get {
                return ResourceManager.GetString("ModuleXLoaded_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Y Loaded.
        /// </summary>
        internal static string ModuleYLoaded_Silverlight {
            get {
                return ResourceManager.GetString("ModuleYLoaded_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Z Loaded.
        /// </summary>
        internal static string ModuleZLoaded_Silverlight {
            get {
                return ResourceManager.GetString("ModuleZLoaded_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefiningModulesInCode.Silverlight.
        /// </summary>
        internal static string SilverlightAppTitleDefineModulesInCode {
            get {
                return ResourceManager.GetString("SilverlightAppTitleDefineModulesInCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoteModuleLoading.Silverlight.
        /// </summary>
        internal static string SilverlightAppTitleRemoteModule {
            get {
                return ResourceManager.GetString("SilverlightAppTitleRemoteModule", resourceCulture);
            }
        }
    }
}
