//===================================================================================
// Microsoft patterns & practices
// Composite Application Guidance for Windows Presentation Foundation and Silverlight
//===================================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===================================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===================================================================================
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commanding.Tests.AcceptanceTest.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlIdentifiers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlIdentifiers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Commanding.Tests.AcceptanceTest.TestData.ControlIdentifiers", typeof(ControlIdentifiers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateLabel.
        /// </summary>
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateLabel.
        /// </summary>
        internal static string DateLabel_SilverLight {
            get {
                return ResourceManager.GetString("DateLabel_SilverLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryDateTextBox.
        /// </summary>
        internal static string DeliveryDateTextBox {
            get {
                return ResourceManager.GetString("DeliveryDateTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryDateTextBox.
        /// </summary>
        internal static string DeliveryDateTextBox_SilverLight {
            get {
                return ResourceManager.GetString("DeliveryDateTextBox_SilverLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell.
        /// </summary>
        internal static string DesktopApplicationTitle {
            get {
                return ResourceManager.GetString("DesktopApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderListView.
        /// </summary>
        internal static string OrderListView {
            get {
                return ResourceManager.GetString("OrderListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderListView.
        /// </summary>
        internal static string OrderListView_SilverLight {
            get {
                return ResourceManager.GetString("OrderListView_SilverLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNameLabel.
        /// </summary>
        internal static string OrderNameLabel {
            get {
                return ResourceManager.GetString("OrderNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNameLabel.
        /// </summary>
        internal static string OrderNameLabel_SilverLight {
            get {
                return ResourceManager.GetString("OrderNameLabel_SilverLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceLabel.
        /// </summary>
        internal static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceLabel.
        /// </summary>
        internal static string PriceLabel_SilverLight {
            get {
                return ResourceManager.GetString("PriceLabel_SilverLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceTextBox.
        /// </summary>
        internal static string PriceTextBox {
            get {
                return ResourceManager.GetString("PriceTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceTextBox.
        /// </summary>
        internal static string PriceTextBox_SilverLight {
            get {
                return ResourceManager.GetString("PriceTextBox_SilverLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantityLabel.
        /// </summary>
        internal static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantityLabel.
        /// </summary>
        internal static string QuantityLabel_SilverLight {
            get {
                return ResourceManager.GetString("QuantityLabel_SilverLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantityTextBox.
        /// </summary>
        internal static string QuantityTextBox {
            get {
                return ResourceManager.GetString("QuantityTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantityTextBox.
        /// </summary>
        internal static string QuantityTextBox_SilverLight {
            get {
                return ResourceManager.GetString("QuantityTextBox_SilverLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveAllToolBarButton.
        /// </summary>
        internal static string SaveAllToolBarButton {
            get {
                return ResourceManager.GetString("SaveAllToolBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveAllToolBarButton.
        /// </summary>
        internal static string SaveAllToolBarButton_SilverLight {
            get {
                return ResourceManager.GetString("SaveAllToolBarButton_SilverLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveButton.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveButton.
        /// </summary>
        internal static string SaveButton_SilverLight {
            get {
                return ResourceManager.GetString("SaveButton_SilverLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingLabel.
        /// </summary>
        internal static string ShippingLabel {
            get {
                return ResourceManager.GetString("ShippingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingLabel.
        /// </summary>
        internal static string ShippingLabel_SilverLight {
            get {
                return ResourceManager.GetString("ShippingLabel_SilverLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingTextBox.
        /// </summary>
        internal static string ShippingTextBox {
            get {
                return ResourceManager.GetString("ShippingTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingTextBox.
        /// </summary>
        internal static string ShippingTextBox_SilverLight {
            get {
                return ResourceManager.GetString("ShippingTextBox_SilverLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commanding.Silverlight.
        /// </summary>
        internal static string SilverlightAppTitle {
            get {
                return ResourceManager.GetString("SilverlightAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalLabel.
        /// </summary>
        internal static string TotalLabel {
            get {
                return ResourceManager.GetString("TotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalLabel.
        /// </summary>
        internal static string TotalLabel_SilverLight {
            get {
                return ResourceManager.GetString("TotalLabel_SilverLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalTextBox.
        /// </summary>
        internal static string TotalTextBox {
            get {
                return ResourceManager.GetString("TotalTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalTextBox.
        /// </summary>
        internal static string TotalTextBox_SilverLight {
            get {
                return ResourceManager.GetString("TotalTextBox_SilverLight", resourceCulture);
            }
        }
    }
}
