//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTraderRI.AcceptanceTests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlIdentifiers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlIdentifiers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTraderRI.AcceptanceTests.TestData.ControlIdentifiers", typeof(ControlIdentifiers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArticleBody.
        /// </summary>
        internal static string ArticleBody {
            get {
                return ResourceManager.GetString("ArticleBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArticlePublishedDate.
        /// </summary>
        internal static string ArticlePublishedDate {
            get {
                return ResourceManager.GetString("ArticlePublishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArticleTitle.
        /// </summary>
        internal static string ArticleTitle {
            get {
                return ResourceManager.GetString("ArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyRadio.
        /// </summary>
        internal static string BuyRadio {
            get {
                return ResourceManager.GetString("BuyRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyLastButton.
        /// </summary>
        internal static string BuySellBuyLastButton {
            get {
                return ResourceManager.GetString("BuySellBuyLastButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelAllToolbarButton.
        /// </summary>
        internal static string BuySellCancelAllButton {
            get {
                return ResourceManager.GetString("BuySellCancelAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelButton.
        /// </summary>
        internal static string BuySellCancelButton {
            get {
                return ResourceManager.GetString("BuySellCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy/Sell.
        /// </summary>
        internal static string BuySellListHeader {
            get {
                return ResourceManager.GetString("BuySellListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderTypeCombo.
        /// </summary>
        internal static string BuySellOrderTypeCombo {
            get {
                return ResourceManager.GetString("BuySellOrderTypeCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SellLastButton.
        /// </summary>
        internal static string BuySellSellLastButton {
            get {
                return ResourceManager.GetString("BuySellSellLastButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharesTextBox.
        /// </summary>
        internal static string BuySellSharesTextBox {
            get {
                return ResourceManager.GetString("BuySellSharesTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopLimitPriceTextBox.
        /// </summary>
        internal static string BuySellStopLimitPriceTextBox {
            get {
                return ResourceManager.GetString("BuySellStopLimitPriceTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitAllToolbarButton.
        /// </summary>
        internal static string BuySellSubmitAllButton {
            get {
                return ResourceManager.GetString("BuySellSubmitAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitButton.
        /// </summary>
        internal static string BuySellSubmitButton {
            get {
                return ResourceManager.GetString("BuySellSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TickerSymbolTextBox.
        /// </summary>
        internal static string BuySellSymbolTextBox {
            get {
                return ResourceManager.GetString("BuySellSymbolTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeInForceCombo.
        /// </summary>
        internal static string BuySellTimeInForceCombo {
            get {
                return ResourceManager.GetString("BuySellTimeInForceCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollapsibleTab.
        /// </summary>
        internal static string CollapsibleRegion {
            get {
                return ResourceManager.GetString("CollapsibleRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompositeExpander.
        /// </summary>
        internal static string CompositeExpander {
            get {
                return ResourceManager.GetString("CompositeExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to articlesView.
        /// </summary>
        internal static string NewsArticlesView {
            get {
                return ResourceManager.GetString("NewsArticlesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NewsButtonName {
            get {
                return ResourceManager.GetString("NewsButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrdersListBox.
        /// </summary>
        internal static string OrdersListBox {
            get {
                return ResourceManager.GetString("OrdersListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionBuySellTab.
        /// </summary>
        internal static string PositionBuySellTab {
            get {
                return ResourceManager.GetString("PositionBuySellTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _positionTable.
        /// </summary>
        internal static string PositionTableId {
            get {
                return ResourceManager.GetString("PositionTableId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SellRadio.
        /// </summary>
        internal static string SellRadio {
            get {
                return ResourceManager.GetString("SellRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelAllToolbarButton.
        /// </summary>
        internal static string ToolbarCancelAllButton {
            get {
                return ResourceManager.GetString("ToolbarCancelAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelToolbarButton.
        /// </summary>
        internal static string ToolbarCancelButton {
            get {
                return ResourceManager.GetString("ToolbarCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitAllToolbarButton.
        /// </summary>
        internal static string ToolbarSubmitAllButton {
            get {
                return ResourceManager.GetString("ToolbarSubmitAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitToolbarButton.
        /// </summary>
        internal static string ToolbarSubmitButton {
            get {
                return ResourceManager.GetString("ToolbarSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddWatchButton.
        /// </summary>
        internal static string WatchListAddButton {
            get {
                return ResourceManager.GetString("WatchListAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddWatchTextBox.
        /// </summary>
        internal static string WatchListAddTextBox {
            get {
                return ResourceManager.GetString("WatchListAddTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WatchListCloseButton.
        /// </summary>
        internal static string WatchListCloseButton {
            get {
                return ResourceManager.GetString("WatchListCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch List.
        /// </summary>
        internal static string WatchListHeader {
            get {
                return ResourceManager.GetString("WatchListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WatchListAutoHideButton.
        /// </summary>
        internal static string WatchListHideButton {
            get {
                return ResourceManager.GetString("WatchListHideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watchListListView.
        /// </summary>
        internal static string WatchListView {
            get {
                return ResourceManager.GetString("WatchListView", resourceCulture);
            }
        }
    }
}
