//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTraderRI.AcceptanceTests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestDataInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestDataInput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTraderRI.AcceptanceTests.TestData.TestDataInput", typeof(TestDataInput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failing the test cases as the application failed to load.
        /// </summary>
        internal static string ApplicationLoadFailure {
            get {
                return ResourceManager.GetString("ApplicationLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102.5.
        /// </summary>
        internal static string BuySellLimitPrice {
            get {
                return ResourceManager.GetString("BuySellLimitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string BuySellNumberOfShares {
            get {
                return ResourceManager.GetString("BuySellNumberOfShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        internal static string BuySellOrderType {
            get {
                return ResourceManager.GetString("BuySellOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUY &amp; SELL.
        /// </summary>
        internal static string BuySellTab {
            get {
                return ResourceManager.GetString("BuySellTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAKEINDEX.
        /// </summary>
        internal static string DefaultCompositeTrendView {
            get {
                return ResourceManager.GetString("DefaultCompositeTrendView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of day.
        /// </summary>
        internal static string FormattedTimeInForceEndOfDay {
            get {
                return ResourceManager.GetString("FormattedTimeInForceEndOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconUri.
        /// </summary>
        internal static string IconUri {
            get {
                return ResourceManager.GetString("IconUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid.
        /// </summary>
        internal static string InvalidString {
            get {
                return ResourceManager.GetString("InvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC-XYZ.
        /// </summary>
        internal static string InvalidSymbol {
            get {
                return ResourceManager.GetString("InvalidSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastPrice.
        /// </summary>
        internal static string LastPrice {
            get {
                return ResourceManager.GetString("LastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   STOCK0.
        /// </summary>
        internal static string LeadingBlankSpacePositionSymbol {
            get {
                return ResourceManager.GetString("LeadingBlankSpacePositionSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketHistoryItem.
        /// </summary>
        internal static string MarketHistoryItem {
            get {
                return ResourceManager.GetString("MarketHistoryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOCK1.
        /// </summary>
        internal static string MarketTickerSymbol {
            get {
                return ResourceManager.GetString("MarketTickerSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOCK6.
        /// </summary>
        internal static string PositionSymbol {
            get {
                return ResourceManager.GetString("PositionSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOCK0.
        /// </summary>
        internal static string PositionSymbol1 {
            get {
                return ResourceManager.GetString("PositionSymbol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOCK3.
        /// </summary>
        internal static string PositionSymbol3 {
            get {
                return ResourceManager.GetString("PositionSymbol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSITION.
        /// </summary>
        internal static string PositionTab {
            get {
                return ResourceManager.GetString("PositionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Basis.
        /// </summary>
        internal static string PositionTableCost {
            get {
                return ResourceManager.GetString("PositionTableCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain Loss %.
        /// </summary>
        internal static string PositionTableGainLoss {
            get {
                return ResourceManager.GetString("PositionTableGainLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string PositionTableHeaderNews {
            get {
                return ResourceManager.GetString("PositionTableHeaderNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string PositionTableLast {
            get {
                return ResourceManager.GetString("PositionTableLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Value.
        /// </summary>
        internal static string PositionTableMarketValue {
            get {
                return ResourceManager.GetString("PositionTableMarketValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string PositionTableNews {
            get {
                return ResourceManager.GetString("PositionTableNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares.
        /// </summary>
        internal static string PositionTableShares {
            get {
                return ResourceManager.GetString("PositionTableShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string PositionTableSymbol {
            get {
                return ResourceManager.GetString("PositionTableSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishedDate.
        /// </summary>
        internal static string PublishedDate {
            get {
                return ResourceManager.GetString("PublishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string SpaceCharacter {
            get {
                return ResourceManager.GetString("SpaceCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ƒund¥.
        /// </summary>
        internal static string SpecialCharacterSymbol {
            get {
                return ResourceManager.GetString("SpecialCharacterSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOCK0.
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TickerSymbol.
        /// </summary>
        internal static string TickerSymbol {
            get {
                return ResourceManager.GetString("TickerSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endofday.
        /// </summary>
        internal static string TimeInForceEndOfDay {
            get {
                return ResourceManager.GetString("TimeInForceEndOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOCK0  .
        /// </summary>
        internal static string TrailingBlankSpacePositionSymbol {
            get {
                return ResourceManager.GetString("TrailingBlankSpacePositionSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOCK7.
        /// </summary>
        internal static string WatchListSymbol {
            get {
                return ResourceManager.GetString("WatchListSymbol", resourceCulture);
            }
        }
    }
}
