//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modularity.Tests.AcceptanceTests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestDataInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestDataInput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modularity.Tests.AcceptanceTests.TestData.TestDataInput", typeof(TestDataInput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failing the test cases as the application failed to load.
        /// </summary>
        internal static string ApplicationLoadFailure {
            get {
                return ResourceManager.GetString("ApplicationLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string ContentString {
            get {
                return ResourceManager.GetString("ContentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dependencies.
        /// </summary>
        internal static string DependenciesNode {
            get {
                return ResourceManager.GetString("DependenciesNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleName.
        /// </summary>
        internal static string DependencyAttributeDirLookup {
            get {
                return ResourceManager.GetString("DependencyAttributeDirLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dependency.
        /// </summary>
        internal static string DependencyNode {
            get {
                return ResourceManager.GetString("DependencyNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module A Loaded.
        /// </summary>
        internal static string ModuleAContent {
            get {
                return ResourceManager.GetString("ModuleAContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module B Loaded.
        /// </summary>
        internal static string ModuleBContent {
            get {
                return ResourceManager.GetString("ModuleBContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module C Loaded.
        /// </summary>
        internal static string ModuleCContent {
            get {
                return ResourceManager.GetString("ModuleCContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module D Loaded.
        /// </summary>
        internal static string ModuleDContent {
            get {
                return ResourceManager.GetString("ModuleDContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moduleName.
        /// </summary>
        internal static string ModuleNameAttribute {
            get {
                return ResourceManager.GetString("ModuleNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module.
        /// </summary>
        internal static string ModuleSectionName {
            get {
                return ResourceManager.GetString("ModuleSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string ModulesFolder {
            get {
                return ResourceManager.GetString("ModulesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to startupLoaded.
        /// </summary>
        internal static string StartupLoadingAttributeConfigDriven {
            get {
                return ResourceManager.GetString("StartupLoadingAttributeConfigDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartupLoaded.
        /// </summary>
        internal static string StartupLoadingAttributeDirLookup {
            get {
                return ResourceManager.GetString("StartupLoadingAttributeDirLookup", resourceCulture);
            }
        }
    }
}
